[package]
name = "redox-cli"
version.workspace = true
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
redox-protocol = { path = "../redox-protocol" }
clap = { version = "4.5", features = ["derive"] }
