[package]
name = "redox-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "redoxd"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
bytes = "1.5"
redox-protocol = { path = "../redox-protocol" }
clap = { version = "4.5", features = ["derive"] } 